webtalk_init -webtalk_dir /home/osama/Desktop/CS224/Labs/Lab 5/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 12 11:58:34 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94e6f971-d96d-4ece-a4f0-9f269c254fd6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "175e19b2a3de46aeadce0834ca3ac64d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "211" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1616.256 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130176_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3263805456 -regid "" -xml /home/osama/Desktop/CS224/Labs/Lab 5/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/osama/Desktop/CS224/Labs/Lab 5/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/osama/Desktop/CS224/Labs/Lab 5/Lab 5/Lab 5.sim/sim_1/behav/xsim/xsim.dir/processor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
